"entities"
{
	"0"
	{
		"name"			"Heal 1"
		"shortname"		"Heal 1"
		"color"			"{default}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"588880"
		"mode"			"2"
		"maxuses"		"0"
		"cooldown"		"55"
		"maxamount"		"2"
	}
	"1"
	{
		"name"			"Earth 1"
		"shortname"		"Earth 1"
		"color"			"{orange}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"589156"
		"mode"			"2"
		"maxuses"		"0"
		"cooldown"		"50"
		"maxamount"		"2"
	}
	"2"
	{
		"name"			"Water 1"
		"shortname"		"Water 1"
		"color"			"{lightblue}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"1780536"
		"mode"			"2"
		"maxuses"		"0"
		"cooldown"		"50"
		"maxamount"		"2"
	}
	"3"
	{
		"name"			"Wind 1"
		"shortname"		"Wind 1"
		"color"			"{green}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"2774402"
		"mode"			"2"
		"maxuses"		"0"
		"cooldown"		"50"
		"maxamount"		"2"
	}
	"4"
	{
		"name"			"Death"
		"shortname"		"Death"
		"color"			"{purple}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"2678814"
		"mode"			"1"
		"maxuses"		"0"
		"cooldown"		"50"
		"maxamount"		"2"
	}
	"5"
	{
		"name"			"Curse"
		"shortname"		"Curse"
		"color"			"{darkorange}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"2678952"
		"mode"			"1"
		"maxuses"		"0"
		"cooldown"		"50"
		"maxamount"		"2"
	}
	"6"
	{
		"name"			"Haste"
		"shortname"		"Haste"
		"color"			"{olive}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"2678960"
		"mode"			"1"
		"maxuses"		"0"
		"cooldown"		"50"
		"maxamount"		"2"
	}
	"7"
	{
		"name"			"Heal 2"
		"shortname"		"Heal 2"
		"color"			"{default}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"907102"
		"mode"			"2"
		"maxuses"		"0"
		"cooldown"		"55"
		"maxamount"		"2"
	}
	"8"
	{
		"name"			"Earth 2"
		"shortname"		"Earth 2"
		"color"			"{orange}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"908910"
		"mode"			"2"
		"maxuses"		"0"
		"cooldown"		"50"
		"maxamount"		"2"
	}
	"9"
	{
		"name"			"Water 2"
		"shortname"		"Water 2"
		"color"			"{lightblue}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"1781491"
		"mode"			"2"
		"maxuses"		"0"
		"cooldown"		"50"
		"maxamount"		"2"
	}
	"10"
	{
		"name"			"Wind 2"
		"shortname"		"Wind 2"
		"color"			"{green}"
		"buttonclass"		"func_button"
		"filtername"		""
		"hasfiltername"		"false"
		"blockpickup"		"false"
		"allowtransfer"		"false"
		"forcedrop"		"false"
		"chat"			"true"
		"hud"			"true"
		"hammerid"		"2786917"
		"mode"			"2"
		"maxuses"		"0"
		"cooldown"		"50"
		"maxamount"		"2"
	}
}